### ISSUE TITLE
Proton Error on Install first time

### ISSUE THREAD

**Issue by muzzethesnd** [Zerschranzer/Linux-ASA-Server-Manager#29]
I Installed the ASA Manger like your guide and run the ./ark_instance*.sh after it downloaded everything sucessfully it errors the following lines. 
After that it says "INITAL SETUP COMPLETED" if i use the number 2 (list instances) it shows "No Instances Found in '/home/*/ark/instances' Dunno whats going on here (Fresh install of everything dont change anything.)
Pls Help :D 
[EDIT] My System is Ubuntu 20.04.6 LTS

`
Proton prefix initialized.
Starting server once to generate configuration files... This will take 60 seconds
Proton: Upgrading prefix from None to GE-Proton10-4 (/home/muzzeserver/server/ark/server-files/steamapps/compatdata/2430930/)
Traceback (most recent call last):
  File "/home/muzzeserver/server/ark/GE-Proton10-4/proton", line 2055, in <module>
    import protonfixes
  File "/home/muzzeserver/server/ark/GE-Proton10-4/protonfixes/__init__.py", line 8, in <module>
    from . import fix
  File "/home/muzzeserver/server/ark/GE-Proton10-4/protonfixes/fix.py", line 12, in <module>
    from .util import ProtonVersion
  File "/home/muzzeserver/server/ark/GE-Proton10-4/protonfixes/util.py", line 25, in <module>
    from .config import config
  File "/home/muzzeserver/server/ark/GE-Proton10-4/protonfixes/config.py", line 40, in <module>
    config = Config(Path.home() / '.config/protonfixes/config.ini')
  File "/home/muzzeserver/server/ark/GE-Proton10-4/protonfixes/config_base.py", line 61, in __init__
    self.init_sections()
  File "/home/muzzeserver/server/ark/GE-Proton10-4/protonfixes/config_base.py", line 86, in init_sections
    section_name = member_name.removesuffix('Section')
AttributeError: 'str' object has no attribute 'removesuffix'
`

**Comment by muzzethesnd** [comment]
#24 -> on Ubuntu 20.X install python 3.9 then change the path on GE-Proton*/proton first line from python3 to python3.9 save.
Redo ark_instance manager with setup (1 on choice) -> fixed and done. 
In Proton the subscript protonfixes need python 3.9 - import protonfixes only works with Python 3.9 . 
Now everything is working. Thx to #24 for reference!

**Comment by Zerschranzer** [comment]
Completely rewrote the script and moved from standalone GE-Proton to umu-launcher. This issue shouldn't apply to the new version. Closing.
